### ISSUE TITLE
Error with the Add ons  est Your Pronunciation (Cloud Speech to Text)

### ISSUE THREAD

**Issue by Angel225588** [rroessler1/speech-to-text#15]
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 23.10.1 (fac9e0ee) Python 3.9.15 Qt 6.5.3 PyQt 6.5.3
Platform: macOS-14.3-arm64-arm-64bit
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-12-18 00:25:05
Add-ons possibly involved: ⁨Test Your Pronunciation Cloud Speech to Text⁩

Caught exception:
Traceback (most recent call last):
  File "/Users/macbook/Library/Application Support/Anki2/addons21/673333980/__init__.py", line 38, in settings_dialog
    SettingsDialog(app_settings, stt_provider, mw).show()
  File "/Users/macbook/Library/Application Support/Anki2/addons21/673333980/__init__.py", line 230, in __init__
    layout.setAlignment(Qt.AlignTop)
AttributeError: type object 'Qt' has no attribute 'AlignTop'

**Comment by rroessler1** [comment]
I updated the add-on for Anki version 23.10.1 and it should be working now.  I'll close this, please re-open it if you keep having issues!

And I apologize for the significant delay in responding, I hadn't worked on this for quite some time.

**Comment by rroessler1** [comment]
Also, please upvote the add-on here if it's working now and you use the add-on, I would be very grateful, and upvotes give it a bit more visibility: https://ankiweb.net/shared/info/673333980
