### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by thiagopikcius** [rroessler1/speech-to-text#16]
After creating Google and Microsoft API keys, when I first tried to open "Test your Pronunciation Settings" in Tools, I got the following message:

Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 23.10.1 (fac9e0ee) Python 3.9.15 Qt 6.6.0 PyQt 6.6.0
Platform: Windows-10-10.0.22621
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2024-02-19 10:07:52
Add-ons possibly involved: ⁨Test Your Pronunciation Cloud Speech to Text⁩

Caught exception:
Traceback (most recent call last):
  File "C:\Users\Thiago\AppData\Roaming\Anki2\addons21\673333980\__init__.py", line 38, in settings_dialog
    SettingsDialog(app_settings, stt_provider, mw).show()
  File "C:\Users\Thiago\AppData\Roaming\Anki2\addons21\673333980\__init__.py", line 230, in __init__
    layout.setAlignment(Qt.AlignTop)
AttributeError: type object 'Qt' has no attribute 'AlignTop'

**Comment by rroessler1** [comment]
I'll have a look, it hopefully just has to be updated for the latest version of Anki.

**Comment by rroessler1** [comment]
I updated the add-on and it should be working now.  I'll close this, please re-open it if you keep having issues.

**Comment by rroessler1** [comment]
Also, please upvote the add-on here if it's working now and you use the add-on, I would be very grateful, and upvotes give it a bit more visibility: https://ankiweb.net/shared/info/673333980
