### ISSUE TITLE
UnicodeDecodeError (Windows specific?) with dragonmapper

### ISSUE THREAD

**Issue by tomshalev** [rroessler1/speech-to-text#2]
I get the following error:

When loading 'Test Your Pronunciation Google Speech to Text':
Traceback (most recent call last):
File "aqt\addons.py", line 211, in loadAddons
File "C:\Users\tomsh\AppData\Roaming\Anki2\addons21\673333980\__init_py", line 15, in <module>
from . vendor.dragonmapper import hanzi
File "C:\Users\tomsh\AppData\Roaming\Anki2\addons21\673333980\_vendor\dragonmapper\hanzi.py",
line 14, in <module>
from .dragonmapper.transcriptions import (
File "C:
\Users\tomsh\AppData\Roaming\Anki2\addons21\673333980\_vendor\dragonmapper\transcriptions.py",
line 59, in <module>
_PINYIN_MAP, _ZHUYIN_MAP, _IPA_MAP = _load_data0
File "C:
\Users\tomsh\AppData\Roaming\Anki2\addons21\673333980\_vendor\dragonmapper\transcriptions.py",
line 50, in _load_data
lines = dragonmapper.data.load_data_file("./transcriptions.csv')
File "C:
%3D
\Users\tomsh\AppData\Roaming\Anki2\addons21\673333980\_vendor\dragonmapper\data\_init_.py",
line 22, in load_data_file
return open((os.path.dirname(os.path.realpath(_file_) + /' + filename)).read(.splitlines()
File "C:\python38\lib\encodings\cp1252.py", line 23, in decode
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 269: character maps to
<undefined>

Thanks for the help

**Comment by rroessler1** [comment]
Thanks for the bug report!  Can you clarify:
-Do you receive this error immediately when starting Anki?
-What version of Windows are you using?
-Was the add-on ever working for you?

**Comment by tomshalev** [comment]
Thank you for replying so quickly!

I will clarify:
-I receive this error immediately when starting Anki.
-I am using Windows 10 Home and my version is 20H2
-and unfortunately, the add-on has never worked for me

I will appriciate any help, as I believe this add-on is vital

Thanks in advance

**Comment by rroessler1** [comment]
I'm looking into this now

**Comment by rroessler1** [comment]
I fixed this and updated the add-on.  Could you update it and confirm that it's working for you?

**Comment by tomshalev** [comment]
I've updated it and it all work perfect now! Thank you very much for your help.

I have a question, do you think it will be possible to add Microsoft Azure Speech to Text as well?

**Comment by rroessler1** [comment]
Awesome, thanks for the confirmation!  Happy to hear it.  Thanks for the bug report, since I don't run Windows I had no idea it wasn't working for it.

If you do find the add-on useful, I'd definitely appreciate a review: https://ankiweb.net/shared/info/673333980 , hopefully it will help other people find and use it :)

Yes, I do plan on adding Microsoft Azure Speech to Text... that's likely the next thing I'll work on.  My understanding was that Google Speech to Text was the most accurate and that's why I started with it.  I need to research other STT services and see who has the best accuracy.

**Comment by rroessler1** [comment]
Hey @tomshalev , happy to report that I just finished adding support for Microsoft Azure Speech to Text, which also has a very generous free tier :)

Hope you enjoy and are still finding the addon useful!
